### ISSUE TITLE
Always Producing "Nothing to Download"

### ISSUE THREAD

**Issue by taylorpaynedev** [iamatulsingh/pinscrape#26]
I am not sure if this is because of a recent change to the code or Pinterest changing their site but the scraper will not pickup any unique URLs. When scraping it will pick up the URLs of Boards that are related to the key words but will not pull images from those boards.

**Comment by iamatulsingh** [comment]
Hi @mentaldropouts, which version are you using?

**Comment by taylorpaynedev** [comment]
I believe the first time I used pinscrape I was using 3.0.3 but when 3.0.3 didn’t work I tried the latest version and it also had the same error.

**Comment by iamatulsingh** [comment]
Thanks for you issue. Please install the latest version is 3.2.2 using `pip install pinscrape==3.2.2`. I ran the test for this version and it works perfectly. Don't hesitate to reopen this issue.
