### ISSUE TITLE
Just "Nothing to download"

### ISSUE THREAD

**Issue by 3r1sn5** [iamatulsingh/pinscrape#28]
Hi, I tried to use Pinscrape to collect some images today, but it keeps showing nothing to download. 
I'm not really familiar with internet/web-related issues, so I'm not sure what's wrong. I remember using the same program to scrape images yesterday, and it worked perfectly fine.
I installed 3.2.2

**Comment by iamatulsingh** [comment]
Hi @3r1sn5 , could you tell me keyword you used? I tried running version 3.2.2 and it's working perfectly fine for me.

**Comment by tharsim** [comment]
I am having the exact same issue using version 3.2.2.

In my case, I am using keyword "sunset". 

```
from pinscrape import pinscrape

details = pinscrape.scraper.scrape("sunset", r'D:\_sunset', {}, 10, 25)

if details["isDownloaded"]:
    print("\nDownloading completed !!")
    print(f"\nTotal urls found: {len(details['extracted_urls'])}")
    print(f"\nTotal images downloaded (including duplicate images): {len(details['url_list'])}")
    print(details)
else:
    print("\nNothing to download !!")
```

And it returns `Nothing do download !!`

Here's `pip show pinscrape`:

```
Name: pinscrape
Version: 3.2.2
Summary: Pinterest | a simple data scraper for pinterest
Home-page: https://github.com/iamatulsingh/pinscrape
Author: Atul Singh
Author-email: atulsingh0401@gmail.com
License:
Location: C:\Users\<redacted>
Requires: beautifulsoup4, opencv-python, pydotmap, pytest, requests
Required-by: #N/A
```

**Comment by 3r1sn5** [comment]
> Hi @3r1sn5 , could you tell me keyword you used? I tried running version 3.2.2 and it's working perfectly fine for me.

I've tried several keywords to test but still the same. 
Like transformers, anime characters, etc.

**Comment by iamatulsingh** [comment]
I just tried 4-5 keywords and everything worked. Hard to understand where is the issue. could you please try "print(details)" in the else condition and send what it prints?

**Comment by tharsim** [comment]
Does this help in any way? Thank you very much @iamatulsingh 

```
python .\run_pinscrape.py

Nothing to download !!
{'isDownloaded': False, 'search_engine_status_code': 200, 'url_list': [], 'extracted_urls': [], 'keyword': 'sunset'}
```

**Comment by iamatulsingh** [comment]
pytest -sv .\e2e.py                                                                                                                                                        ─╯
============================================================================= test session starts ==============================================================================
platform win32 -- Python 3.11.4, pytest-7.2.0, pluggy-1.0.0 -- C:\Users\AtulSingh\miniconda3\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\AtulSingh\Documents\pinscrape
plugins: anyio-4.0.0
collected 1 item

e2e.py::test_single_data 
Downloading completed !!

Total urls found: 1

Total images downloaded (including duplicate images): 1
{'isDownloaded': True, 'search_engine_status_code': 200, 'url_list': ['https://i.pinimg.com/originals/65/c1/0a/65c10aa6b20b6fcdedb309667dab7f97.jpg'], 'extracted_urls': ['https://www.pinterest.com/just1wayticket/sunset'], 'keyword': 'sunset'}
PASSED

============================================================================== 1 passed in 3.07s ===============================================================================


I ran the test with many keywords including "sunset" but it's working. I'll try to understand if I can do something. Atleast I'll try to add few more data in next minor version to know what is the issue.

**Comment by tharsim** [comment]
Thank you! I am a newbie, but when I installed the non-packaged version yesterday (which was also returning `Nothing to download !!`), I had to upgrade `setuptools wheel` because I was getting `subprocess-exited-with-error`. That was the only thing I had to do that diverted from the instructions. I wonder if that's connected to the problem.

**Comment by iamatulsingh** [comment]
@tharsim / @3r1sn5 I have pushed new release v3.2.3 where I have added urls that scraped from seacrh engine and then download performed. This you can install and then again send the printed data here. If you see, again the [test](https://github.com/iamatulsingh/pinscrape/actions/runs/9798593350/job/27057294746) get passed that means image is still getting downloaded.

**Comment by tharsim** [comment]
It's working! I was able to download the sunset images now

```
python .\run_pinscrape.py

Downloading completed !!

Total urls found: 11
Traceback (most recent call last):
  File "D:\<redacted>\pinscrape\run_pinscrape.py", line 8, in <module>
    print(f"\nTotal images downloaded (including duplicate images): {len(details['url_list'])}")
                                                                         ~~~~~~~^^^^^^^^^^^^
KeyError: 'url_list'
```

**Comment by iamatulsingh** [comment]
Cool! if you think that was it, you can close the issue.

**Comment by tharsim** [comment]
Thank you. The OP is @3r1sn5 😄

**Comment by iamatulsingh** [comment]
Sorry my bad. @3r1sn5 you can test the latest version and give me your response.

**Comment by 3r1sn5** [comment]
@iamatulsingh It's working for me too. Many thanks! :)
