### ISSUE TITLE
it doawnloads more pictures than I want

### ISSUE THREAD

**Issue by ODOshmocke** [iamatulsingh/pinscrape#3]

**Comment by iamatulsingh** [comment]
Hi @ODOshmocke,
This library doesn't contain any code that give you ability to download limited images for you. You can control by your side.

**Comment by reemelmahdi** [comment]
How can one control the number of images to be downloaded?

**Comment by iamatulsingh** [comment]
It's not possible at this moment but it's a nice idea. I'll implemented that as soon as getting time.

**Comment by iamatulsingh** [comment]
@ReemOmer , you can now use download limitation. Just update the version and enjoy. It's added by @Adair-GA
