### ISSUE TITLE
ERROR While installing in Python

### ISSUE THREAD

**Issue by ubaidseo001** [iamatulsingh/pinscrape#5]
It is giving error while running pip that this code requires visual studio 14 however there has been an updated version.

**Comment by iamatulsingh** [comment]
That's not a error for my code. You may need visual studio for Opencv which is a library used by the code. You can open issue in there github. Since it's not related to this library.

**Comment by ubaidseo001** [comment]
Thanks alot. Do you have any other code for automating pins ? This one is a Great work...

**Comment by iamatulsingh** [comment]
Thank you. Sorry but this is the only one.

**Comment by ubaidseo001** [comment]
Thanks alot Buddy. This worked great. Can we have a .txt file of description as well ? and The pin title as image name ? Sorry i dont have much py knowledge i a just a script noob.

**Comment by iamatulsingh** [comment]
You can easily create a .txt or json file from description like
```python
import json
with open('json_data.json', 'w') as outfile:
    outfile.write(json.dumps(details))
```
Also, I can't set pin title as image name as the pin title can be duplicate which will cause overwriting image.

**Comment by makseem77** [comment]
> It is giving error while running pip that this code requires visual studio 14 however there has been an updated version.

Hello I have the same issue, how did you resolve it ?
