### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by makseem77** [iamatulsingh/pinscrape#6]
Is the scraping random ? Is there a way to scrape the first results ?

**Comment by iamatulsingh** [comment]
It's not random. It always scrape first to last results.

**Comment by makseem77** [comment]
Oh okay, it's weird I don't get the same results when I do the research manually. Do you have an idea why ?

**Comment by iamatulsingh** [comment]
May be because Google results differ. But may be you can pull the code and debug the result once.

**Comment by makseem77** [comment]
oh okay, if i understand well (i don't know much about coding sorry), the scraper does a research for "my keyword" + "pinterest" in google ? not directly in pinterest ?

**Comment by iamatulsingh** [comment]
True, I did this way so at least we can give credit to the original author of those images and don't have to use official API too.

**Comment by makseem77** [comment]
I see, so in theory I could even remove the "pinterest" to scrape images from google directly right ?

**Comment by iamatulsingh** [comment]
Yes you can change that but the code is written to scrape data from Pinterest so it will not work with any other websites. You'll need to change the code according to your need.

**Comment by makseem77** [comment]
I see, thanks for your answers !

**Comment by iamatulsingh** [comment]
No problem at all.
