### ISSUE TITLE
Failed to build numpy during installation

### ISSUE THREAD

**Issue by amoghvaishampayan** [iamatulsingh/pinscrape#8]
While installing pinscrape I get the error -

ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

Any idea how to fix this?

**Comment by iamatulsingh** [comment]
It's not a problem with this project. You may want to check if C++
libraries are installed on your system. May be something else but it's
related to building numpy.

**Comment by filipkry** [comment]
@iamatulsingh 
I got the same error while installing to the newest python release 3.11.3.
Seems like pinscrape tries to install all dependecies including opencv-python==4.5.3.56 which does not support python 3.11.3.
I am able to install the the newer release opencv-python 4.7.0.72 without a problem, contrary opencv-python 4.5.3.56 is always throwing problem. Can you please update the version of opencv-python in dependecies or just allow newer opencv-python release while installing pinscrape? 
Thanks for any suggestions

**Comment by iamatulsingh** [comment]
I'll test this today with python 3.11 and update here.

**Comment by iamatulsingh** [comment]
I've allowed Opencv latest version to install now. You can try the pinscrape==2.0.1 which is also a latest version now, to test this and let me know.

**Comment by filipkry** [comment]
Firstly, let me to thank you for the support!
I will test it later today.

**Comment by iamatulsingh** [comment]
My pleasure. Take your time.

**Comment by filipkry** [comment]
@iamatulsingh 
Now works perfectly! Thanks again!

**Comment by iamatulsingh** [comment]
No problem.
